#spring:
#  data:
#    redis:
#      host: ${AUTH_REDIS_HOST}
#      port: ${AUTH_REDIS_PORT}
#      password:
#  datasource:
#    url: ${AUTH_DATASOURCE_URL}
#    username: ${AUTH_DATASOURCE_USERNAME}
#    password: ${AUTH_DATASOURCE_PASSWORD}
#    jpa:
#      hibernate:
#        ddl-auto: none
#    flyway:
#      enabled: true
#      locations: classpath:db/migration
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${SMTP_EMAIL}
#    password: ${SMTP_APP_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    default-encoding: UTF-8
#  kafka:
#    bootstrap-servers: cinemate-broker:${CINEMATE_BROKER_PORT}
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    template:
#      default-topic: user-registered
#server:
#  port: ${AUTH_SERVICE_PORT}
#app:
#  auth:
#    access-token-secret: ${ACCESS_TOKEN_SECRET}
#    access-token-expiration-msec: 7200000
#    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
#    refresh-token-expiration-msec: 2592000000
#  admin:
#    email: ${AUTH_ADMIN_EMAIL}
#    password: ${AUTH_ADMIN_PASSWORD}
#    first-name: ${AUTH_ADMIN_FIRST_NAME}
#    last-name: ${AUTH_ADMIN_LAST_NAME}
#
#web-url: ${WEB_URL}
