spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5832/cinemate_payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: giabao7112004@gmail.com
    password: jsit bkwt ncpk gioj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  port: 8996

app:
  auth:
    access-token-secret: Ckj2tdZqqx4zYqn0iSB9bUPIsckWdFoa/YIi1kzGWKc9qM5XCbRoPHmWhft9pZZCGeKYcAhgILzOu++4toDC0Gn9iDWTlRAlnQ8efRnVU8I=
    access-token-expiration-msec: 900000
    refresh-token-secret: Ckj2tdZqqx4zYqn0iSB9bUPIsckWdFoa/YIi1kzGWKc9qM5XCbRoPHmWhft9pZZCGeKYcAhgILzOu++4toDC0Gn9iDWTlRAlnQ8efRnVU8I=
    refresh-token-expiration-msec: 604800000
  email:
    from: ${EMAIL_FROM:noreply@cinemate.com}
    from-name: ${EMAIL_FROM_NAME:Cinemate Team}
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: 1HFIAMAT
  hash-secret: CADXA3EU1ARGTN6ZDVVDEVGTZWDEDSSB
  return-url: https://985e02b7dbd5.ngrok-free.app/api/payments/vnpay-return
  ipn-url: https://985e02b7dbd5.ngrok-free.app/api/payments/vnpay-ipn
