spring:
  datasource:
    url: ${DEV_CUSTOMER_DB_URL}
    username: ${DEV_CUSTOMER_DB_USERNAME}
    password: ${DEV_CUSTOMER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:${DEV_CINEMATE_BROKER_HOST_PORT}
    consumer:
      group-id: customer-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer




server:
  port: ${DEV_CUSTOMER_SERVICE_PORT}

app:
  auth:
    access-token-secret: ${DEV_ACCESS_TOKEN_SECRET}
    access-token-expiration-msec: 7200000