spring:
  datasource:
    url: jdbc:postgresql://${CUSTOMER_POSTGRES_HOST}:${CUSTOMER_POSTGRES_PORT}/${CUSTOMER_POSTGRES_DB}
    username: ${CUSTOMER_POSTGRES_USER}
    password: ${CUSTOMER_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${CINEMATE_BROKER_HOST}:${CINEMATE_BROKER_PORT}
    consumer:
      group-id: customer-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.pbl6.events"
server:
  port: ${CUSTOMER_SERVICE_PORT:8080}

app:
  auth:
    access-token-secret: ${ACCESS_TOKEN_SECRET}
    access-token-expiration-msec: 7200000
  minio:
    url: ${MINIO_URL}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket-name: images
