spring:
  profiles:
    active: dev
  application:
    name: customer-service
  kafka:
    bootstrap-servers: localhost:9095
    consumer:
      group-id: customer-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.pbl6.events"

server:
  servlet:
    context-path: /customers

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html