spring:
  data:
    redis:
      host: ${DEV_AUTH_REDIS_HOST}
      port: ${DEV_AUTH_REDIS_PORT}
      password:
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DEV_ADMIN_EMAIL}
    password: ${DEV_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  kafka:
    bootstrap-servers: localhost:${DEV_CINEMATE_BROKER_HOST_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: user-registered

server:
  port: ${DEV_AUTH_SERVICE_PORT}

app:
  auth:
    access-token-secret: ${ACCESS_TOKEN_SECRET}
    access-token-expiration-msec: 7200000
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    refresh-token-expiration-msec: 2592000000
  admin:
    email: ${DEV_ADMIN_EMAIL}
    password: ${DEV_ADMIN_PASSWORD}
    first-name: ${DEV_ADMIN_FIRST_NAME}
    last-name: ${DEV_ADMIN_LAST_NAME}

web-url: ${DEV_WEB_URL}
