spring:
  data:
    redis:
      host: ${REDIS_HOST:cinemate-redis}
      port: ${REDIS_PORT:6379}
      password:
  datasource:
    url: ${AUTH_DATASOURCE_URL}
    username: ${AUTH_DATASOURCE_USERNAME}
    password: ${AUTH_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_EMAIL}
    password: ${SMTP_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:cinemate-broker:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: user-registered
server:
  port: ${SERVICE_PORT:8585}
app:
  auth:
    access-token-secret: ${ACCESS_TOKEN_SECRET}
    access-token-expiration-msec: ${ACCESS_TOKEN_EXPIRY:7200000}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    refresh-token-expiration-msec: ${REFRESH_TOKEN_EXPIRY:2592000000}
  admin:
    email: ${AUTH_ADMIN_EMAIL}
    password: ${AUTH_ADMIN_PASSWORD}
    first-name: ${AUTH_ADMIN_FIRST_NAME}
    last-name: ${AUTH_ADMIN_LAST_NAME}

web-url: ${WEB_URL:http://localhost:3000}
